version: '3.8'

services:
  scholarship:
    container_name: scholarship_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8002:8000"
    env_file:
      - .env

networks:
  default:
    external:
      name: atlas-network
