# Generated by Django 6.0.5 on 2026-05-15 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarship', '0003_scholarship_registration_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentBankRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.UUIDField(help_text='UUID do aluno registrado no banco de talentos')),
                ('is_actively_looking', models.BooleanField(default=True, verbose_name='Buscando oportunidades?')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interviewer_id', models.UUIDField(help_text='UUID do professor')),
                ('description', models.TextField(blank=True, help_text='Notas ou feedback da entrevista')),
                ('interview_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarship.application')),
                ('talent_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='talent.talentbankregistration')),
            ],
        ),
    ]
