# Generated by Django 6.0.5 on 2026-05-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentbankregistration',
            old_name='student',
            new_name='student_id',
        ),
    ]
