# Generated by Django 6.0.5 on 2026-05-19 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_rename_student_talentbankregistration_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(help_text='UUID do aluno registrado no banco de talentos')),
                ('orientador_id', models.UUIDField(help_text='UUID do professor orientador')),
                ('content', models.TextField(blank=True, help_text='Notas ou feedback do orientador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(help_text='UUID do aluno registrado no banco de talentos')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Fulfilled', 'Fulfilled'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('status_changed_by', models.UUIDField(blank=True, help_text='UUID do usuário que alterou o status do talento', null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InterviewRecord',
        ),
        migrations.DeleteModel(
            name='TalentBankRegistration',
        ),
    ]
