# Generated by Django 6.0.5 on 2026-05-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_note_talent_delete_interviewrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='status_changed_by',
            field=models.UUIDField(blank=True, help_text='UUID do usuário que alterou', null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='student_id',
            field=models.UUIDField(help_text='UUID do aluno registrado no banco de talentos', unique=True),
        ),
    ]
