# Generated by Django 6.0.5 on 2026-05-12 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_in_months', models.PositiveIntegerField(default=1, help_text='Duração em meses')),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('minimum_period', models.PositiveIntegerField(default=1)),
                ('minimum_ira', models.DecimalField(decimal_places=2, max_digits=4)),
                ('orientator_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closing', 'Closing'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Ex: Edital, Anexo I', max_length=255)),
                ('url', models.URLField()),
                ('type', models.CharField(help_text='EDITAL, ATTACHMENT, FORM, OTHER', max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='scholarship.scholarship')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='scholarship.scholarship')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=1)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='scholarship.scholarship')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='technologies',
            field=models.ManyToManyField(related_name='scholarships', to='scholarship.technology'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Enrolled', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarship.scholarship')),
            ],
            options={
                'unique_together': {('scholarship', 'student_id')},
            },
        ),
    ]
