# Generated by Django 6.0.5 on 2026-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshiplink',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scholarshiplink',
            name='type',
            field=models.CharField(choices=[('Edital', 'Edital'), ('Attachment', 'Attachment'), ('Form', 'Form'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarshiprequirement',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
