# Generated by Django 6.0.5 on 2026-05-13 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_scholarshiplink_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='registration_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
