# Generated by Django 5.2.8 on 2026-05-20 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_registration_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(choices=[('technology', 'Technology'), ('scholarship', 'Scholarship'), ('scholarship_link', 'Scholarship Link'), ('scholarship_requirement', 'Scholarship Requirement'), ('scholarship_phase', 'Scholarship Phase'), ('application', 'Application'), ('talent', 'Talent'), ('note', 'Note')], max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('record_id', models.UUIDField(help_text='PK do registro afetado')),
                ('user_id', models.UUIDField(blank=True, help_text='UUID do usuário responsável pela operação', null=True)),
                ('payload', models.JSONField(blank=True, help_text='Snapshot before/after do registro', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
