# Generated by Django 6.0.5 on 2026-06-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='orientator_id',
            new_name='published_by',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='registration_start',
        ),
        migrations.RemoveField(
            model_name='scholarshiplink',
            name='type',
        ),
        migrations.AddField(
            model_name='scholarshipphase',
            name='type',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Selection', 'Selection'), ('Result', 'Result'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('RegistrationClosed', 'Registration Closed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipphase',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
