# Generated by Django 6.0.5 on 2026-06-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Enrolled', 'Enrolled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Enrolled', max_length=20),
        ),
    ]
