# Generated by Django 6.0.5 on 2026-06-22 04:26

from django.db import migrations, models


def restore_registration_closed(apps, schema_editor):
    Scholarship = apps.get_model('scholarship', 'Scholarship')
    Scholarship.objects.filter(status='Closing').update(status='RegistrationClosed')


def restore_closing(apps, schema_editor):
    Scholarship = apps.get_model('scholarship', 'Scholarship')
    Scholarship.objects.filter(status='RegistrationClosed').update(status='Closing')


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_rename_registration_closed_status'),
    ]

    operations = [
        migrations.RunPython(restore_registration_closed, restore_closing),
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('RegistrationClosed', 'Registration Closed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
