# Generated by Django 4.2.30 on 2026-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_alter_scholarship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Responsabilidades do bolsista', null=True),
        ),
    ]
